### ISSUE TITLE
Correct broken relative links on About page

### ISSUE THREAD

**Issue by colleenumn** [geobtaa/geobtaa.github.io#80]
Fix the following broken relative links

- [x] Read more about our technical infrastructure on our [Technology Projects page](https://gin.btaa.org/about/technology/projects) should be corrected to `../../technology/projects/`
- [x] [Annual GIS Conference](https://gin.btaa.org/about/conference): should be `../../conference/`
- [x] [Reference Guides](https://gin.btaa.org/about/guides): should be `../../guides/`
- [x] [Educational Resources](https://gin.btaa.org/about/guides): should be `../../tutorials/`
- [ ] As of 2024, we are currently embarking on a [new initiative to collect public geospatial data](https://gin.btaa.org/about/technology/geodata-collection/), should be `../../technology/geodata-collection/`

**Comment by karenmajewicz** [comment]
Thanks for catching these!
